Fix compilation on i386
 The i386 injection code is failing to build (eg. on debian):

 injector.c:817:2: warning: asm operand 7 probably doesn't match constraints
  __asm__ __volatile__ ("\
  ^~~~~~~
 injector.c:817:2: error: impossible constraint in 'asm'

 This is caused partly by the code using relocations which aren't
 available on i386, partly because the code is naive and is
 overwriting 9 registers from memory structure which should be
 referenced by one of the 7 overwritten... That won't work (on x86_64,
 it can work because it has rip-based addressing so you can make it
 overwrite rip at the last instruction).

 This commit fixes it by changing the code to a rather clumsy, but
 robust one. The register used for addressing the memory structure is
 fixed and the code address to jump to is stored on the new stack to
 pop by the ret instruction, which is a common way to change context
 on i386. The only perceivable change from the previous (nonworking)
 code intent is that esp is shifted by 4 (which doesn't matter because
 its precise address never actually used later in the code).